language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2

matrix:
  fast_finish: true
  allow_failures: false

install:
  - composer install
  
script:
  - vendor/bin/phpspec run
